In [1]:
import numpy as np
import pandas as pd

In [15]:
x_train = pd.read_csv('Data/X_train.csv')
x_test = pd.read_csv('Data/X_test.csv')
y_train = pd.read_csv('Data/y_train.csv')
y_test = pd.read_csv('Data/y_test.csv')

x_train.head()

,filghtId,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,duration,days_left
0,252589,Vistara,UK-808,Bangalore,Early_Morning,one,Night,Mumbai,13.25,46
1,223754,Vistara,UK-927,Delhi,Morning,one,Evening,Chennai,10.42,31
2,243398,Vistara,UK-988,Mumbai,Night,one,Morning,Chennai,13.00,28
3,208360,Vistara,UK-815,Delhi,Morning,one,Night,Mumbai,12.67,17
4,247226,Vistara,UK-854,Bangalore,Evening,one,Morning,Delhi,13.67,32

In [16]:
df1 = pd.concat([x_train, x_test], ignore_index=True)
df1.head(10)

,filghtId,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,duration,days_left
0,252589,Vistara,UK-808,Bangalore,Early_Morning,one,Night,Mumbai,13.25,46
1,223754,Vistara,UK-927,Delhi,Morning,one,Evening,Chennai,10.42,31
2,243398,Vistara,UK-988,Mumbai,Night,one,Morning,Chennai,13.00,28
3,208360,Vistara,UK-815,Delhi,Morning,one,Night,Mumbai,12.67,17
4,247226,Vistara,UK-854,Bangalore,Evening,one,Morning,Delhi,13.67,32
5,293881,Vistara,UK-822,Chennai,Morning,one,Morning,Bangalore,23.08,11
6,254119,Vistara,UK-814,Bangalore,Night,one,Evening,Kolkata,22.42,21
7,272356,Vistara,UK-772,Kolkata,Morning,one,Early_Morning,Hyderabad,21.42,45
8,271143,Vistara,UK-778,Kolkata,Afternoon,one,Afternoon,Hyderabad,21.25,20
9,256513,Vistara,UK-850,Bangalore,Evening,one,Night,Hyderabad,25.00,11

In [17]:
df1.shape

(9045, 10)

In [18]:
df2 = pd.concat([y_train,y_test],ignore_index=True)
df2.head()

   filghtId  price
0    252589  69244
1    223754  52392
2    243398  61933
3    208360  53164
4    247226  42521

In [19]:
df = pd.merge(df1,df2,on='filghtId')
df.head()

,filghtId,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,duration,days_left,price
0,252589,Vistara,UK-808,Bangalore,Early_Morning,one,Night,Mumbai,13.25,46,69244
1,223754,Vistara,UK-927,Delhi,Morning,one,Evening,Chennai,10.42,31,52392
2,243398,Vistara,UK-988,Mumbai,Night,one,Morning,Chennai,13.00,28,61933
3,208360,Vistara,UK-815,Delhi,Morning,one,Night,Mumbai,12.67,17,53164
4,247226,Vistara,UK-854,Bangalore,Evening,one,Morning,Delhi,13.67,32,42521

In [7]:
df.shape

(9045, 11)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9045 entries, 0 to 9044
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   filghtId          9045 non-null   int64
 1   airline           9045 non-null   object
 2   flight            9045 non-null   object
 3   source_city       9045 non-null   object
 4   departure_time    9045 non-null   object
 5   stops             9045 non-null   object
 6   arrival_time      9045 non-null   object
 7   destination_city  9045 non-null   object
 8   duration          9045 non-null   float64
 9   days_left         9045 non-null   int64
 10  price             9045 non-null   int64
dtypes: float64(1), int64(3), object(7)
memory usage: 777.4+ KB

In [9]:
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder

In [10]:
le = LabelEncoder()
stdsc = StandardScaler()
ohe = OneHotEncoder()

In [11]:
df.head(10)

,filghtId,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,duration,days_left,price
0,252589,Vistara,UK-808,Bangalore,Early_Morning,one,Night,Mumbai,13.25,46,69244
1,223754,Vistara,UK-927,Delhi,Morning,one,Evening,Chennai,10.42,31,52392
2,243398,Vistara,UK-988,Mumbai,Night,one,Morning,Chennai,13.00,28,61933
3,208360,Vistara,UK-815,Delhi,Morning,one,Night,Mumbai,12.67,17,53164
4,247226,Vistara,UK-854,Bangalore,Evening,one,Morning,Delhi,13.67,32,42521
5,293881,Vistara,UK-822,Chennai,Morning,one,Morning,Bangalore,23.08,11,44144
6,254119,Vistara,UK-814,Bangalore,Night,one,Evening,Kolkata,22.42,21,62188
7,272356,Vistara,UK-772,Kolkata,Morning,one,Early_Morning,Hyderabad,21.42,45,49207
8,271143,Vistara,UK-778,Kolkata,Afternoon,one,Afternoon,Hyderabad,21.25,20,62255
9,256513,Vistara,UK-850,Bangalore,Evening,one,Night,Hyderabad,25.00,11,37985

In [20]:
del df['filghtId']
del df['flight']
df.head(10)

,airline,source_city,departure_time,stops,arrival_time,destination_city,duration,days_left,price
0,Vistara,Bangalore,Early_Morning,one,Night,Mumbai,13.25,46,69244
1,Vistara,Delhi,Morning,one,Evening,Chennai,10.42,31,52392
2,Vistara,Mumbai,Night,one,Morning,Chennai,13.00,28,61933
3,Vistara,Delhi,Morning,one,Night,Mumbai,12.67,17,53164
4,Vistara,Bangalore,Evening,one,Morning,Delhi,13.67,32,42521
5,Vistara,Chennai,Morning,one,Morning,Bangalore,23.08,11,44144
6,Vistara,Bangalore,Night,one,Evening,Kolkata,22.42,21,62188
7,Vistara,Kolkata,Morning,one,Early_Morning,Hyderabad,21.42,45,49207
8,Vistara,Kolkata,Afternoon,one,Afternoon,Hyderabad,21.25,20,62255
9,Vistara,Bangalore,Evening,one,Night,Hyderabad,25.00,11,37985

In [21]:
df['airline'].value_counts()

airline
Vistara      5831
Air_India    3195
Indigo          6
GO_FIRST        5
SpiceJet        4
AirAsia         4
Name: count, dtype: int64

In [22]:
# removing rare categories

threshold = 50  # minimum rows to keep
def category_filter(df,col):
    
    counts = df[col].value_counts()
    valid_categories = counts[counts >= threshold].index

    df = df[df[col].isin(valid_categories)]
    return df
df = category_filter(df,'airline')
df = category_filter(df,'departure_time')
df['airline'].value_counts()

airline
Vistara      5831
Air_India    3191
Name: count, dtype: int64

In [23]:
columns = ['airline','source_city','departure_time','stops','arrival_time','destination_city']

for col in columns:
    df[col] = le.fit_transform(df[col])
     
    print(f"\nColumn: {col}")
    print("Mapping:", dict(zip(le.classes_, le.transform(le.classes_))))
    print(df[col].value_counts())

Column: airline
Mapping: {'Air_India': np.int64(0), 'Vistara': np.int64(1)}
airline
1    5831
0    3191
Name: count, dtype: int64

Column: source_city
Mapping: {'Bangalore': np.int64(0), 'Chennai': np.int64(1), 'Delhi': np.int64(2), 'Hyderabad': np.int64(3), 'Kolkata': np.int64(4), 'Mumbai': np.int64(5)}
source_city
5    1901
2    1799
0    1658
4    1245
3    1224
1    1195
Name: count, dtype: int64

Column: departure_time
Mapping: {'Afternoon': np.int64(0), 'Early_Morning': np.int64(1), 'Evening': np.int64(2), 'Morning': np.int64(3), 'Night': np.int64(4)}
departure_time
3    2238
2    2020
1    1939
4    1650
0    1175
Name: count, dtype: int64

Column: stops
Mapping: {'one': np.int64(0), 'two_or_more': np.int64(1), 'zero': np.int64(2)}
stops
0    8159
2     768
1      95
Name: count, dtype: int64

Column: arrival_time
Mapping: {'Afternoon': np.int64(0), 'Early_Morning': np.int64(1), 'Evening': np.int64(2), 'Late_Night': np.int64(3), 'Morning': np.int64(4), 'Night': np.int64(5)}
arrival_time
5    2807
2    2474
4    2082
0    1097
1     367
3     195
Name: count, dtype: int64

Column: destination_city
Mapping: {'Bangalore': np.int64(0), 'Chennai': np.int64(1), 'Delhi': np.int64(2), 'Hyderabad': np.int64(3), 'Kolkata': np.int64(4), 'Mumbai': np.int64(5)}
destination_city
5    1834
2    1599
0    1533
4    1414
3    1371
1    1271
Name: count, dtype: int64

In [24]:
df.head()

,airline,source_city,departure_time,stops,arrival_time,destination_city,duration,days_left,price
0,1,0,1,0,5,5,13.25,46,69244
1,1,2,3,0,2,1,10.42,31,52392
2,1,5,4,0,4,1,13.00,28,61933
3,1,2,3,0,5,5,12.67,17,53164
4,1,0,2,0,4,2,13.67,32,42521

In [101]:
df.info

<bound method DataFrame.info of       airline  source_city  departure_time  stops  arrival_time  \
0           1            0               1      0             5
1           1            2               3      0             2
2           1            5               4      0             4
3           1            2               3      0             5
4           1            0               2      0             4
...       ...          ...             ...    ...           ...
9040        0            1               2      0             4
9041        1            2               1      0             5
9042        1            2               1      0             5
9043        1            0               2      0             4
9044        1            0               1      0             5

      destination_city  duration  days_left  price
0                    5     13.25         46  69244
1                    1     10.42         31  52392
2                    1     13.00         28  61933
3                    5     12.67         17  53164
4                    2     13.67         32  42521
...                ...       ...        ...    ...
9040                 5     17.17         36  61649
9041                 0     15.17          9  54777
9042                 5     13.83         27  59033
9043                 1     15.08         28  60396
9044                 3     15.92         38  56588

[9022 rows x 9 columns]>

### Scaling

In [25]:
columns = ['duration','days_left']

for col in columns:
    df[col] = stdsc.fit_transform(df[[col]])
df.head()

,airline,source_city,departure_time,stops,arrival_time,destination_city,duration,days_left,price
0,1,0,1,0,5,5,-0.063280,1.493911,69244
1,1,2,3,0,2,1,-0.477039,0.384149,52392
2,1,5,4,0,4,1,-0.099832,0.162196,61933
3,1,2,3,0,5,5,-0.148079,-0.651630,53164
4,1,0,2,0,4,2,-0.001875,0.458133,42521

In [26]:
X = df.drop('price',axis=1)
y = df['price']

X.head()

,airline,source_city,departure_time,stops,arrival_time,destination_city,duration,days_left
0,1,0,1,0,5,5,-0.063280,1.493911
1,1,2,3,0,2,1,-0.477039,0.384149
2,1,5,4,0,4,1,-0.099832,0.162196
3,1,2,3,0,5,5,-0.148079,-0.651630
4,1,0,2,0,4,2,-0.001875,0.458133

In [27]:
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.model_selection import KFold, cross_val_score

## Using KFold Cross Validation we compare 4 diff models

In [28]:
kf = KFold(n_splits=5,shuffle=True,random_state=42)

In [29]:
def kcross(model,X,y,cv):

    r2_scores = cross_val_score(model, X, y, cv=cv,scoring='r2')
    
    print(f'Model Used:{model}')
    print(f'R2 Scores:{r2_scores}')
    print(f'Mean R2:{r2_scores.mean()}')
    print(f'Standard Deviation R2:{r2_scores.std()}')

In [30]:
kcross(LinearRegression(),X,y,kf)

Model Used:LinearRegression()
R2 Scores:[0.3903943  0.38259412 0.35895184 0.39461143 0.40092153]
Mean R2:0.38549464401579353
Standard Deviation R2:0.014546785652313887

In [31]:
kcross(SVR(kernel='rbf'),X,y,kf)

Model Used:SVR()
R2 Scores:[ 0.00183522 -0.00229676 -0.00039255 -0.00027834 -0.00200279]
Mean R2:-0.0006270435767049331
Standard Deviation R2:0.001477834967459054

In [32]:
rf = RandomForestRegressor(
    n_estimators=300,
    max_depth=None,
    random_state=42,
    n_jobs=-1
)
kcross(rf,X,y,kf)

Model Used:RandomForestRegressor(n_estimators=300, n_jobs=-1, random_state=42)
R2 Scores:[0.75943908 0.75623069 0.74889851 0.76052841 0.75898904]
Mean R2:0.7568171447029399
Standard Deviation R2:0.004205089407082489

In [33]:
xgb = XGBRegressor(
    n_estimators=300,
    learning_rate=0.1,
    max_depth=6,
    subsample=0.8,
    random_state=42,
    objective='reg:squarederror',
    n_jobs=-1,
    tree_method='hist'
)

kcross(xgb,X,y,kf)

Model Used:XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=300,
             n_jobs=-1, num_parallel_tree=None, ...)
R2 Scores:[0.7432574  0.74569082 0.73345965 0.75797051 0.74344301]
Mean R2:0.7447642803192138
Standard Deviation R2:0.007836760739029341

In [34]:
from sklearn.model_selection import train_test_split

X_train,X_test, y_train,y_test = train_test_split(X,y,test_size=0.20)

### Through K-Fold Cross Validation we get Best model RandomForestRegressor

In [35]:
from sklearn.model_selection import GridSearchCV

In [36]:
rf = RandomForestRegressor(random_state=42)

## HyperParameter Tuning using GridSearchCV

In [37]:
param_grid = {
    'n_estimators': [100, 200, 300],           # number of trees
    'max_depth': [None, 10, 20, 30],          # max depth of trees
    'min_samples_split': [2, 5, 10],          # min samples to split a node
    'min_samples_leaf': [1, 2, 4],            # min samples at leaf node
    'max_features': ['auto', 'sqrt', 0.5],    # number of features for split
    'bootstrap': [True]                # use bootstrap samples
}

In [38]:
grid = GridSearchCV(estimator=rf,
                    param_grid=param_grid,
                    cv=5,                  # 5-fold cross-validation
                    scoring='r2',  # regression metric
                    n_jobs=-1,             # use all cores
                    verbose=2)

In [39]:
grid.fit(X_train,y_train)

Fitting 5 folds for each of 324 candidates, totalling 1620 fits

D:\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning:
540 fits failed out of a total of 1620.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
540 fits failed with the following error:
Traceback (most recent call last):
  File "D:\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\Anaconda\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\Anaconda\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
D:\Anaconda\Lib\site-packages\sklearn\model_selection\_search.py:1135: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan 0.72942286 0.73065424 0.73079747
 0.72135794 0.72293929 0.72406093 0.70411583 0.70441518 0.70547635
 0.71227145 0.71415013 0.71487031 0.71286531 0.71230157 0.71296908
 0.6966711  0.69795671 0.69891867 0.6849092  0.68539256 0.68603351
 0.6849092  0.68539256 0.68603351 0.68247343 0.68302136 0.68345007
 0.73016903 0.73107669 0.73234904 0.72914194 0.73085525 0.7308216
 0.7145145  0.71597064 0.71642132 0.725004   0.72567174 0.72602483
 0.72307522 0.72397812 0.72446356 0.71225198 0.71229775 0.71262804
 0.70426618 0.70516223 0.70517536 0.70426618 0.70516223 0.70517536
 0.70341161 0.70334627 0.70380824        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.63956653 0.63869674 0.63881947 0.63941725 0.63837601 0.63894997
 0.63475316 0.6351614  0.63542509 0.63666277 0.63634734 0.63682031
 0.63568564 0.63577922 0.63556705 0.63280567 0.63345921 0.6336355
 0.62876911 0.62940622 0.63004698 0.62876911 0.62940622 0.63004698
 0.62851929 0.62750797 0.62767249 0.65315542 0.65404512 0.65434333
 0.65333195 0.6549032  0.65500891 0.65158526 0.65276137 0.65277288
 0.65365865 0.65471405 0.65483413 0.6531697  0.65406155 0.65387974
 0.65161837 0.65241498 0.65207051 0.64972489 0.65132643 0.65121254
 0.64972489 0.65132643 0.65121254 0.64990683 0.65090907 0.65031285
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan 0.72578259 0.72774821 0.72800918
 0.72151536 0.72272707 0.72330426 0.70398815 0.70385147 0.70503246
 0.7135791  0.7136391  0.71398928 0.71137399 0.71118067 0.71213705
 0.69698401 0.6982424  0.69888739 0.6848872  0.68563798 0.68595282
 0.6848872  0.68563798 0.68595282 0.68184793 0.6829883  0.683349
 0.72948749 0.73103349 0.73170207 0.72865007 0.7299241  0.72988327
 0.71377316 0.71537085 0.71607917 0.72539322 0.72585572 0.72632828
 0.72191883 0.72330127 0.72382662 0.71188596 0.71223033 0.7122671
 0.70392476 0.70481397 0.7050319  0.70392476 0.70481397 0.7050319
 0.70313463 0.70328041 0.70344625        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.72945064 0.7306796  0.73078616 0.72136953 0.72293731 0.72404104
 0.70411583 0.70441518 0.70547635 0.71227145 0.71415013 0.71487031
 0.71286531 0.71230157 0.71296908 0.6966711  0.69795671 0.69891867
 0.6849092  0.68539256 0.68603351 0.6849092  0.68539256 0.68603351
 0.68247343 0.68302136 0.68345007 0.73015707 0.7310366  0.73231555
 0.72913791 0.73086578 0.73082305 0.7145145  0.71597064 0.71643011
 0.72498197 0.72566074 0.7260081  0.7230501  0.72396627 0.72448013
 0.71225198 0.71229775 0.71262804 0.70426618 0.70516223 0.70517536
 0.70426618 0.70516223 0.70517536 0.70341161 0.70334627 0.70380824]
  warnings.warn(

GridSearchCV(cv=5, estimator=RandomForestRegressor(random_state=42), n_jobs=-1,
             param_grid={'bootstrap': [True], 'max_depth': [None, 10, 20, 30],
                         'max_features': ['auto', 'sqrt', 0.5],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [100, 200, 300]},
             scoring='r2', verbose=2)

In [41]:
best_param = grid.best_params_
best_model = grid.best_estimator_

print(f'Best Model:{best_model}')
print(f'Best Parameters:{best_param}')

Best Model:RandomForestRegressor(max_features=0.5, n_estimators=300, random_state=42)
Best Parameters:{'bootstrap': True, 'max_depth': None, 'max_features': 0.5, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 300}

In [42]:
y_pred = best_model.predict(X_test)

In [46]:
from sklearn.metrics import r2_score as r2
from sklearn.metrics import root_mean_squared_error as rmse
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import mean_absolute_error as mae

In [48]:
print(f'R2:{r2(y_test,y_pred)}')
print(f'RMSE:{rmse(y_test,y_pred)}')
print(f'MSE:{mse(y_test,y_pred)}')
print(f'MAE:{mae(y_test,y_pred)}')

R2:0.7743814210768001
RMSE:6193.846942756539
MSE:38363739.95029452
MAE:3901.9667597194743

In [51]:
import pickle

# Saving the model using pkl

with open('rf_model.pkl', 'wb') as f:
    pickle.dump(best_model, f)